### ISSUE TITLE
Important!!! Promote this Press Release

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#107]
Hey Guys, I figured we would drop it here to the activist community first. 

Here is the press release announcing that Vlad Zamfir, will be the 7th Board of Director for the RChain Cooperative and help guide our Casper Proof-of-Stake implementation

https://docs.google.com/viewer?url=https://github.com/rchain/board/raw/master/Vlad%20Zamfir%20joins%20the%20RChain%20Cooperative.pdf

Let's get this picked up by as many media sites that are relevant as possible. Its ok if we overlap in our outreach. 

I suggest we reach out to coindesk, cointelegraph, cryprt0 show, smith and crown, epicenter, and whichever ones that you can think of else. 

Also social media messaging such as tweets and a reddit post will be going out soon so that we can boost the reach.

Cheers!

**Comment by llerner** [comment]
I don't see a link?

**Comment by patrick727** [comment]
@llerner added it!

**Comment by dckc** [comment]
It would be easier to promote if it had a more traditional URL like https://www.rchain.coop/news/2017/09/​zamfir​-joins-rchain ... one that's clearly owned by rchain.

**Comment by dckc** [comment]
Oh... now I see google docs is just being used as a viewer. https://github.com/rchain/board/raw/master/Vlad%20Zamfir%20joins%20the%20RChain%20Cooperative.pdf works too. That's a little better, but [sharecropping][] on github still isn't ideal, especially when it's not social coding.

[sharecropping]: https://www.tbray.org/ongoing/When/200x/2003/07/12/WebsThePlace

**Comment by patrick727** [comment]
@dckc  those are good points, right now i'm working with what was given. 

Here are the linked tweets 
https://twitter.com/rchain_coop/status/911062616222715906 
https://twitter.com/rchain_coop/status/911063763599667201

**Comment by djrtwo** [comment]
Both links are broken for me on mobile btw.

**Comment by djrtwo** [comment]
Or at least from my mobile mail. I copied the PDF link and pasted to
browser and it worked. Exciting news!

**Comment by patrick727** [comment]
@djrtwo thanks for the pointer! and yes very Exciting, can't wait to see what the co-op looks like by the time Mercury gets released! Medha is doing a great job as well with project management too makes me feel very confident.

**Comment by patrick727** [comment]
Here is the reddit thread https://www.reddit.com/r/CryptoCurrency/comments/71og5p/vlad_zamfir_joins_the_rchain_cooperative/

**Comment by djrtwo** [comment]
I threw it onto /r/ethtrader. Those guys usually get pretty hyped up about
Vlad.

https://www.reddit.com/r/ethtrader/comments/71ohhp/casper_research_vlad_zamfir_joins_the_rchain/

**Comment by lapin7** [comment]
@patrick727 @dckc @djrtwo @llerner  Please don't forget to add a budget through form [Budget allocation and spending](https://docs.google.com/forms/d/e/1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA/viewform)

@patrick727 please be careful with assigning people to issues without their consent. Best is that collaborators assign themselves ;-)

@llerner please fill out the form [Activist Registration](https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform). It's necessary for receiving rewards in RHOC. Hopefully the process for Membership and Activists will be soon one. Sorry for the inconvenience.

**Budget allocation**


And please distribute the budget over the assigned collaborators.

**Reward allocation**

URL | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | $ Sep Budget | ⍴ Sep Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/107 | New | Important!!! Promote this Press Release | Marketing | 0 | $ - | $ - | $ - | $ - | ⍴ - |  



107 | https://github.com/rchain/Members/issues/107 | Important!!! Promote this Press Release | Marketing | 0 | New | ⍴ - | $ - | $ - | $ - | Activist | 0% | 0 | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
107 | https://github.com/rchain/Members/issues/107 | Important!!! Promote this Press Release | Marketing | 0 | New | ⍴ - | $ - | $ - |   | @patrick727 | 0% | 0 |  
107 | https://github.com/rchain/Members/issues/107 | Important!!! Promote this Press Release | Marketing | 0 | New | ⍴ - | $ - | $ - |   | @dckc | 0% | 0 |  
107 | https://github.com/rchain/Members/issues/107 | Important!!! Promote this Press Release | Marketing | 0 | New | ⍴ - | $ - | $ - |   | @djrtwo | 0% | 0 |  
107 | https://github.com/rchain/Members/issues/107 | Important!!! Promote this Press Release | Marketing | 0 | New | ⍴ - | $ - | $ - |   | @llerner? | 0% | 0 |

**Comment by patrick727** [comment]
@djrtwo thanks! 

medium post https://medium.com/rchain-cooperative/vlad-zamfir-joins-the-rchain-cooperative-a05f8e32c110

**Comment by patrick727** [comment]
New tweet pairs

https://twitter.com/rchain_coop/status/911209280434515969
https://twitter.com/rchain_coop/status/911209323581313024

**Comment by patrick727** [comment]
retweet this tweet and/or tweet at this guy https://twitter.com/crypt0snews so that he will cover it on his news show, hes got about 50k subs. 

my tweet: https://twitter.com/patrickpresents/status/911210439626850304

**Comment by jimscarver** [comment]
I created a link http://tinyurl.com/RChainVlad

**Comment by patrick727** [comment]
@kdvalentine or @plantether 

are you able to whip up a quick 500-750 word blog post on Vlad joining the Cooperative? 
this will be a guest post for State of the Dapps (ethercasts)

All it needs to do is highlight the news, talk a bit about casper proof of stake, and then talk about the importance of blockchain governance and the reasoning behind doing rchain as a cooperative, and how vlad and kenny are passionate about this. 

If you agree I can create another issue and give it a seperate budget. Please let me know asap thankyou

**Comment by kitblake** [comment]
Upvoted both. This is creating some buzz, great.

**Comment by lapin7** [comment]
**Budget update**
**2 more Activist votes needed for setting the budget** (please find one :-)


URL | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | $ Sep Budget | ⍴ Sep Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/107 | New | Important!!! Promote this Press Release | Marketing | 1 | $ - | $ - | $ 2,500.00 | $ 2,500.00 | ⍴ 25,000.00 | @patrick727

**Comment by lapin7** [comment]
Who wrote [the blog post](https://medium.com/rchain-cooperative/vlad-zamfir-joins-the-rchain-cooperative-a05f8e32c110) on Medium?

**Comment by patrick727** [comment]
@lapin7 the medium post is a direct copy from the press release. 

@kdvalentine said that he would draft up another guest post as well.

**Comment by Ojimadu** [comment]
Hello there, Am new here. Can i write an article on this?

**Comment by jbassiri** [comment]
This is great news! (Sorry for late response been off line for the Jewish new year and Sabbath.) Happy to promote this asap!

-- 
Jacob Bassiri-Tehrani
(516) 458-7439

**Comment by patrick727** [comment]
@Ojimadu great, yes please share it with us and we will review it!

**Comment by Ojimadu** [comment]
Prominent Ethereum Researcher Vlad Zamfir joins R-chain Co-op as Director.
Prominent Ethereum  researcher has joined R-chain cooperative as a director of the platform. Vlad who is popularly known for his work on ethereum’s POS (Proof-of Stake) consensus mechanism ‘Casper’ posted on his twitter handle that he is excited to help the R-chain ecosystem with blockchain governance. 
Until recently, most blockchains such as bitcoin and ethereum uses proof-of-work (POW) as means to arrive at a consensus. Proof-of-work has a major problem, it is highly energy intensive and it is estimated that mining activities associated with proof of work uses more electricity than the whole of Iceland. Also with increasing mining difficulty as in bitcoin’s  POW consensus mechanism raises the barrier of entry to decentralized systems which increases the risk of centralization. In a bid to mitigate these, ethereum’s developers and researchers came up with ‘Casper’.  Casper named after the 1995 American movie is a security-deposit based economic consensus protocol. Which means that nodes has to be bonded validators (place a security deposit) in order to be able to forge blocks. The protocol’s control of the security deposits is one way in which the incentives of validators is affected by casper. Casper uses a mechanism known as ‘slasher’ to disincentivize bad actors and solve the ‘nothing at stake problem’, it does this by making bad actors lose their stake/ bonded security deposit and prevents them from participating in the consensus process when they try to act in a malicious manner. Vlad has been researching casper along with Ethereum founder Vitalik Buterin since 2015.
R-chain is a parallelized blockchain with governance built into it in form of a cooperative. Governance has been a problem for blockchains without an inherent mechanism to govern itself  as has been the case of bitcoin and its block size debate which lingered for more than two years and does not seem to be completely solved. Blockchains with inherent governance mechanism proposes to be faster in pushing upgrades to the network and charting a clear direction  and roadmap without much need for nasty hardforks. Upgrades can voted upon easily by bonded validators or by some other means depending on the type of governance system implemented this help blockchains to be able to adapt and adopt features quickly and help the network grow organically.
R-chain takes quite a different approach to governance it proposes an open cooperative known as co-op which is the organization that develops the open-source RChain platform software.  In R-chain proposals are made along with a budget (if any) by active members of the co-op, proposals are then voted upon by validated members of the co-op. Then co-op is still in its formative stages hence the actually workings of its governance system is yet to be finalized but it is already in used by the community.
Vlad joins Kenny rowe, co-founder of MakerDAO among five other as board directors. Both of which has been are passionate about governance and consensus in distributed systems. 
This comes as the Co-op nears the conclusion of its private token sale, ending September 28, 2017. More information at https://privatesaleinfo.rchain.coop/.

**Comment by patrick727** [comment]
@Ojimadu this is great!, I'd like to see ssomeone with better editing skills thne I(such as @kitblake or @plantether) comb through this for grammer and spelling, one thing that poppoed is its RChain and now R-Chain. 

Overall great stuff, where did you intend to publish this?

**Comment by Ojimadu** [comment]
Was thinking of steemit or medium. I think Medium seem to be better. Anyone can post it elsewhere too.

**Comment by patrick727** [comment]
Awesome, we need some coverage on steemit and medium so please go ahead and post to both and we can swarm like-share it! Great stuff dude lets get you into the activist reward sheet for this issue, or @lapin7  maybe there should be a seperate one for guest posts?

**Comment by plantether** [comment]
Nice work, @Ojimadu!  Attached is a Word doc with some suggested changes and comments. 

[Ojimadu Vlad post comments.docx](https://github.com/rchain/Members/files/1327436/Ojimadu.Vlad.post.comments.docx)

**Comment by Ojimadu** [comment]
@plantether, Nice comments. I've edited the original post here is the medium link

https://medium.com/@Ojimadu/ethereum-researcher-vlad-zamfir-joins-rchain-co-op-board-of-directors-6d70a035d0d8

**Comment by patrick727** [comment]
@Ojimadu awesome, you should submit it to https://medium.com/ethercasts and I will get it accepted and that will broader your reach with it!

**Comment by Ojimadu** [comment]
@patrick727 If it can be done soon, the better.

**Comment by patrick727** [comment]
@Ojimadu yes just request it on their publication

**Comment by Ojimadu** [comment]
@patrick727 how please? Email?

**Comment by patrick727** [comment]
@Ojimadu sorry it has to be on their side, my bad.

I am working on it now

**Comment by patrick727** [comment]
It would be great to email Crypt0 show and ask for them to cover the story. I got one reply so if we follow up with some demand it may help to close things. 

Cheers

**Comment by Ojimadu** [comment]
@patrick727  Sure
