### ISSUE TITLE
gather/publish a list of values that rchain would like to convey in its content

### ISSUE THREAD

**Issue by pythonical** [rchain/Members#110]

**Comment by lapin7** [comment]
**Mission​:**

​​The RChain Cooperative’s mission is to build a decentralized, economically sustainable
public compute infrastructure. The platform boasts a modular, end-to-end design that commits to
correct-by-construction software and industrial extensibility. It’s multi year undertaking and involves
many different part of software components.

The cooperative attracts members that share the mission and the values of the cooperative:
● We make decisions. Decisions have to be supported at least three members.
● We are courageous. We are allowed to do the wrong thing, because otherwise, we can never
do the right thing either.
● We share profits according to SMART participation in results.
● We advance one another. We depend on our cohesion.
● We trust one another. We know that each and every one of us wants the best for the
cooperative.
● We take initiatives and respect those of others.If we see something we dislike, we respond
by making and spreading something we like, instead of pointing out what we dislike. We
need diversity in our activism and strive for it.
● We respect knowledge. In discussing a subject, any subject, hard measured data is
preferable. Second preference goes to a person with experience in the subject.
● We respect the time of others and the focus of the organization.
● We act with dignity. We’re always showing respect in our shaping of public opinion: respect
toward each other, toward newcomers, and toward our adversaries.
● We are long term.
The cooperative has to be managed in a way that the members believe in what they think is best for
the reaching the mission.
