### ISSUE TITLE
M> Work out the A/V setup for streaming presentations in a How-To

### ISSUE THREAD

**Issue by kitblake** [rchain/Members#114]
We need to have a repeatable setup for streaming presentations at meetings and meetups. These usually involve a speaker with a presentation laptop, a host doing the recording and streaming with a controlling laptop, a smartphone recording video, a microphone for the speaker, and audio amplification for the audience. Objective: write a How-To.

**Comment by kitblake** [comment]
The quality of the audio is more important than that of the video, especially for remote viewers.

**Comment by entropee** [comment]
The Video Production group can help with this.

We have a channel called livestreams. I have linked from there to this issue number.

use /dig a to see the channel procedures

(Video Production Group)(https://chat.divvydao.net/video-team/channels/live-streams)

**Comment by kitblake** [comment]
Great! I added "Objective: write a How-To" to the description and title.

**Comment by lapin7** [comment]
**Setting**
Room with audience of 80 people watching a presentation on screen and amplified audio.
Online Zoom-webinar with panellists and attendees
Direct live stream to Youtube

**Hardware setup.**

Apple MacBook Pro (Mac)
Iphone as panellist that is the camera 
Samson Stage PXD1 (wireless mic that plugs in with receiver into Mac usb port)
Samson Expedition XP106 (karaoke box that receives in mp3 port an aux cable from Mac's headphone port)
Philips PicoPix (beamer that receives mini HDMI from Mac's HDMI port)

Apple MacBook Pro (Mac)
![image](https://user-images.githubusercontent.com/1913335/33127007-fcbeae74-cf86-11e7-9d4e-59f2ae1f55a9.png)

Samson Stage PXD1 (wireless mic that plugs in with receiver into Mac usb port)
![image](https://user-images.githubusercontent.com/1913335/33127066-393746f4-cf87-11e7-88b0-aadd07b82633.png)
![image](https://user-images.githubusercontent.com/1913335/33127074-3f6c576c-cf87-11e7-830e-889fd39ce267.png)

Samson Expedition XP106 (karaoke box that receives in mp3 port an aux cable from Mac's headphone port)
![image](https://user-images.githubusercontent.com/1913335/33127018-0b8929fc-cf87-11e7-94c5-22d0ab481bd4.png)
![image](https://user-images.githubusercontent.com/1913335/33127029-179d559c-cf87-11e7-8133-5902f11df4bf.png)
Philips PicoPix (beamer that receives mini HDMI from Mac's HDMI port)
![image](https://user-images.githubusercontent.com/1913335/33127048-27945180-cf87-11e7-885c-f8dab5aa7f4c.png)

**Mac audio settings:**
Device for sound output is: Headphones
Device for sound input: Samson RXD wireless receiver
 
![image](https://user-images.githubusercontent.com/1913335/33127141-84f1acec-cf87-11e7-85a0-b66b3814e291.png)
Device for sound output is: Headphones
![image](https://user-images.githubusercontent.com/1913335/33127183-c0d264b8-cf87-11e7-999e-00b29f762524.png)
Device for sound input: Samson RXD wireless receiver

**Quicktime**
In order to allow sound output, start QuickTime: File new Audio recording. Slide the volume bar to the right.
![image](https://user-images.githubusercontent.com/1913335/33127374-86382940-cf88-11e7-8f95-1e04403959f2.png)

**Zoom setup**
Browse to [Zoom](https://zoom.us)
![image](https://user-images.githubusercontent.com/1913335/33127591-57fce006-cf89-11e7-9928-58cc85a6d881.png)

Tick on My Webinars and then start your webinar.
![image](https://user-images.githubusercontent.com/1913335/33127642-95c79a7a-cf89-11e7-8519-845751a16be3.png)

Tick on broadcast for letting people to join your webinar as panellists. That means that they can participate in your webinar. Attendees can only listen.

Now start your live stream to YouTube. Tick more and and tick Live on Youtube.
Choose your google account.
Type the title of your webinar
Tick Go Live!
![image](https://user-images.githubusercontent.com/1913335/33128035-358d40a4-cf8b-11e7-9dc2-b72dadba4ed5.png)

**Screen configuration of Zoom between Mac and Screen**
Untick Mirror Displays
![image](https://user-images.githubusercontent.com/1913335/33128201-d684416a-cf8b-11e7-96f1-c049a473b546.png)

Choose a small screen to share, i.e. Chrome browser or presentation.
Drag it to the presentation screen.
![image](https://user-images.githubusercontent.com/1913335/33128500-e741ef06-cf8c-11e7-894d-8dd6afb19d3a.png)
Tick full screen green button

On youtube you can see what viewers will see of your webinar.

**Comment by kitblake** [comment]
A note for people trying this: HJ had everything working and I was helping with testing the mic. Then, a few minutes before the Meetup started, it seemed like Zoom ran out of memory or something. Zoom started dropping aspects, like the microphone, behaving like it does when the Internet connection is too slow and it stops updating the video. After a quit and relaunch everything worked again. It might be wise to get everything setup and working and then quit and relaunch 10 minutes before an event starts.
