### ISSUE TITLE
Wiki space about RChain

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#178]
@MParlikar created a publick [Wiki Space](https://rchain.atlassian.net/wiki/spaces/RCHAIN/pages)

Let's see how we can make use of that space

**Comment by patrick727** [comment]
Its very nice,

But I spoke with her yesterday and she would like for us not to push it too hard yet because some of the dates for milestones are fillers and not "official" an she wants to clarify that before linking it out and promoting it greatly.

**Comment by patrick727** [comment]
I believe there should only be 1 "Offical Channel" for reddit, what do you guy think that it should be 

/RChain
/RChain_Official

we can only link to one from official sources and if we own both then we can simply shut one down.

**Comment by Ojimadu** [comment]
Same here. There should only be one official subreddit channel maybe the other can be a fan subreddit. Having two doesn't really cast good light and might be confusing.

**Comment by MParlikar** [comment]
I created a separate space for Members to use the wiki.  You are correct, I
am still in the process of cleaning up the Project sites for roadmap, etc...

But the members have a blank, public space that they can use as they wish.

I hope this clarifies.

Medha

**Comment by kitblake** [comment]
It seems we already have a fan/user sub and an official sub, with:

/RChain
/RChain_Official

We should absolutely not shut /RChain because someone else will create it (for trolling). 

Maybe some active Reddit users want to disagree about the naming convention (I'm not active).

But it's like registering a .com domain, you have to register .org too, or some scammer will. This happened with Monero  (and I know an experienced user who lost a lot). Of course, a scammer can always start an /RChain_OfficiaI sub (where the lowercase l is an uppercase I) but if we have control of the typical addresses, we're properly prepped.

**Comment by patrick727** [comment]
yes, we should secure as many as possible, but determine what is official

i.e accountable mods, links from the website, AMA's, etc

Trolls go wherever there is activity lol

my vote is /RChain_Official

**Comment by dckc** [comment]
We already have https://github.com/rchain/Members/wiki ; somebody tell me a story about how https://rchain.atlassian.net/wiki/spaces/RCHAIN/pages is usefully different?

I could see an argument that github is overly centralized and hence we should set up a wiki in dev.rchain.coop. But I don't see much reason to use rchain.atlassian.net outside the core dev team. Github's community dwarfs atlassian, no?

And how did reddit get into this conversation? How is reddit related to wiki spaces?

**Comment by MParlikar** [comment]
It's not usefully different IMHO.  I wanted to offer it to the membership.
If it is not needed, I have no issues with not using it.

Kind regards,

Medha

**Comment by lapin7** [comment]
Let's close https://rchain.atlassian.net/wiki/spaces/RCHAIN/pages
and work on
 https://github.com/rchain/Members/wiki



--
Cheers,
HJ

**Comment by MParlikar** [comment]
okay!  No problem!
