### ISSUE TITLE
Onboarding request: flesh out your discord profile

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#210]
Onboarding request: flesh out your discord profile a little, everybody. bonus points for your "how I came to RChain" story. But a linkedin profile would be great to keep names / faces straight.
Example item on http://www.madmode.com/ 
( hint: it will go under http://www.madmode.com/search/label/capabilities/ )

$4000

**Comment by kitblake** [comment]
A way to provide links to existing profiles (LinkedIn, Twitter, Medium, Github, personal blog, whatever) would be useful, especially for those in the oh-no-yet-another-profile group.

**Comment by Viraculous** [comment]
Wonderful an idea but the link is not going. I have tried loading the page but it does not

**Comment by ResonanceXX** [comment]
Currently fleshing out my profile. With recent display picture from me at home. This is on my discord. If it's needed in Github, I could change it also.

**Comment by dckc** [comment]
How much of this bounty should I claim? Is $4K for updating everybody's profile? Surely it's not just for my own discord profile and [blog item](http://www.madmode.com/2017/rchain-dev-retreat.html).

**Comment by dckc** [comment]
turns out the link to madmode.com from my profile is a note that only I see.

But I learned we can connect twitter handles etc.

Too bad it doesn't do linkedin; lots of RChain folks use linkedin.

I wish it supported IndieAuth...

**Comment by lapin7** [comment]
@dckc you could claim $4K if you get the folks so enthusiastic that they are going to update their profile. :-)

**Comment by Keaycee** [comment]
How can this be done ?@dckc

**Comment by BelovedAquila** [comment]
@lapin7 please how does one access or contribute to this?because those links which could have been a hint, are not seeming to go through.

**Comment by dckc** [comment]
I recommend against pursuing this further. Even if people add links to their profiles, they're so hard to find that it's not likely to contribute much to a sense of community (to see the my twitter link, you have to know to right click my avatar and choose "profile"). I prefer the spreadsheet that results from the onboarding survey in #222.

As to how to use the limited feature discord supports:
  1. user settings (the gear in the lower left)
  2. Connections
  3. Choose twitter, steam, etc. and continue with the prompts.

A request for [Profile Connections: Github, Bitbucket etc][1] has been pending since March 2017. It's got 576 votes, but who knows whether that motivates discord to do anything about it. Oh... [another one][2] with 1,653 votes.

[1]: https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/18594754-profile-connections-github-bitbucket-etc
[2]: https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/31677793-add-new-accounts-to-the-connections-page
