### ISSUE TITLE
Curation of Content for Newsletter & More

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#26]
Help us deliver the best newsletter we can!

copy and paste 
-important news updates from the slack, 
-newly releases documentation/research from developers
-updates on the coop or holdings
-questions that still need to be answered 
-events coming soon
-related information across industry/markets (legislation, etc)

copy and paste the into this document under the section "Curated Info at the bottom"
[](https://docs.google.com/document/d/1RZIS9vfzp7cUvYs_2EpjzrUnejzb5sXXORK16Ho4JW8/edit#)

**Comment by plantether** [comment]
Greg explains reactive programming

https://youtu.be/oCSpkTofNIo?t=938

Formal methods make faster and safer, so will be able to get transactions rates that will allow them to put data/content directly onto the blockchain.

“Facebook is creating lots of little interactions using the user feed that are almost like mini contracts – this post was seen by X people, click here to boost so Y more people will see, etc."

“Think of all data as incoming live stream (as posts, for example), and you want your programs to be able to react to that incoming stream, and you also programs to be able to create outgoing streams, either by collecting data directly from users, or by filtering other streams and then running processing against those and repacking that as a stream, by aggregating streams, etc.”

“Rchain is a built around a set of computational abstractions that are the next generation of reactive programming. 

“Mobile process calculi is reactive programming 3.0. It’s a way of organizing live streams and interactions and posts all within one single computational model that makes all of that both uniform, so you don’t have to think about 10 different computational models which is what is so complex about internet programming today. But also, it’s in alignment with what is arguably the most performant computational model for big data.

"The computation model at the core of RChain is arguably at the heart of what makes reactive programming so applicable for big data."

RChain: all about big data for the blockchain

Makes programming things like social networks or freelance markets or dating applications and other kinds of streaming applications with audio or video much more approachable within a blockchain world

**Comment by kitblake** [comment]
@patrick727, something for your Trello: we need typographical house style for web/print at some point (esp. needed for contracts). The newsletter could be a pilot.

**Comment by patrick727** [comment]
@kitblake we have type fonts in the style guide, i believe its the "grotesque" category 

https://github.com/rchain/style_guide_and_files/blob/master/rchain_style_guide_r1v2.pdf

is that what you are talking about?

ps i'm almost entirely sure that I spelled that wrong.

**Comment by patrick727** [comment]
I really like the tagline "Big Data for the Blockchain" @plantether alot.

**Comment by kitblake** [comment]
@patrick727, that (nicely done) style guide is for logo usage. We should have a consistent house style for typography in documents that are communicated to the outside world. However that need is not a raging fire to be extinguished at this moment..

**Comment by patrick727** [comment]
@plantether great edits to the newsletter document! thank you very much!

**Comment by lapin7** [comment]
The newsletter "May 2017 Updates" has been prepared through [Rchain/Members/Marketing/Community Dev](https://docs.google.com/document/d/1RZIS9vfzp7cUvYs_2EpjzrUnejzb5sXXORK16Ho4JW8/edit#heading=h.r6yvq2tvr0xb).

But the doc that has been send as a test mail is not one to one with this doc.
Is it possible to write it in MD format, so that everybody can see how it will be finally?

We go now through another edit/comment path by email to a selected group of persons.
It would be great if it can be done github.

**Comment by patrick727** [comment]
Ok no problem HJ. I wanted to get in the habit of setting a deadline, even for community aggregated content.

**Comment by lapin7** [comment]
Of course dealines and milestones are perfect for getting things done.

--
Cheers,
HJ

**Comment by patrick727** [comment]
Guys we did a great job curating content for the last newsletter! This one coming for June 1st is going to be excpecially interesting because we have the events of Consensus 2017, the pencilworks meetup, and Token Summit, along side with Kent teching the noob class, as well as everything else going on. 

https://docs.google.com/document/d/1TiIvU2eXkM4crE0QlxENj54eTifWtZnWwOTdWamn3Y8/edit?usp=sharing

There is a document to the first draft, I will draft up the contents of this into the sendpulse next Monday 5/29 so add as much input as you can throughout the week, this particular issue will be interesting to see the outcome because there's a lot of new happenings. 

Cheers!

**Comment by patrick727** [comment]
ATTENTION if you wish to be included in the test emails for the newsletter, please comment with your email address, the next test will be sent out later today or tomorrow morning.  or @lapin7 can provide me with the emails for the active participants and I will include them into my test list.

**Comment by kitblake** [comment]
Hey @patrick727, could you setup a "Newsletter Test" list on the email service to which people could subscribe? This would also test the sending via the service. I would opt-in..

**Comment by patrick727** [comment]
Right that's what I plan on doing, but I need everyones emails in order to set that list up.

**Comment by patrick727** [comment]
https://docs.google.com/a/noveltymechanics.com/forms/d/e/1FAIpQLSc9eEBpnshqEbgU0mqJa7ozT5Ro0qJklt4eTEU0xvnEnu9d8Q/viewform?usp=sf_link this is google form that you can use to opt into the "Test Emails" moving forward. @kitblake

**Comment by lapin7** [comment]
Activist that got 100 RHOH and paid around $20.00 and who're on Github:
jimscarver@gmail.com
kdvactmgmt@gmail.com
realtyanddesign@gmail.com
fwlhsu@outlook.com
rcbhux@protonmail.com
kitblake@infrae.com
yves89@gmail.com
andrewvam@gmail.com
optictopic@gmail.com
chris@discaux.com
robert@discaux.com
chloe.gross@protonmail.com
takksplace@gmail.com
lapin7@gmail.com
allan.erskine@gmail.com
sam.t.rogers@gmail.com
ervin@lemark.si
grospic@gmail.com
planteater@protonmail.com
gary@oxide.net.au
stephen.a.prior@gmail.com
joao@nicolauoliveira.com
philipeachille@gmail.com

Activists that registered and are at least interest in news mail:
jimscarver@gmail.com
lapin7@gmail.com
patrick.michael@noveltymechanics.com
planteater@protonmail.com
kent@kentshikama.com
rishabhkapoor8711@gmail.com
johntitor1006@outlook.com
admin@hostingboy.net
gary@oxide.net.au
kdvactmgmt@gmail.com
realtyanddesign@gmail.com
grospic@gmail.com
philipp.zollinger@gmx.ch
fwlhsu@outlook.com
rcbhux@protonmail.com
azulmarino@me.com
abdulfinance@hotmail.com
sabimenow@live.com
ChrisMcCown@gmail.com
kitblake@infrae.com
yves89@gmail.com
andrewvam@gmail.com
optictopic@gmail.com
ervin@lemark.si
jgstoner41982@gmail.com
mwila@themodmin.com
sam.t.rogers@gmail.com
allan.erskine@gmail.com
chris@discaux.com
robert@discaux.com
alonc777@gmail.com
herb@democracy.earth
glen@glenbraun.com
twofivesix@tuta.io
chloe.gross@protonmail.com
ryan3nichols@gmail.com
takksplace@gmail.com
mail@benp.net
bodja.martuniv@gmail.com
asindu@coinella.cash
stephen.a.prior@gmail.com
alex@coinfund.io
drbloom@gmail.com
philipeachille@gmail.com
joao@nicolauoliveira.com
wallinpeter@sbcglobal.net
alex@coinfund.io

**Comment by lapin7** [comment]
And there's also a list of 300 email addresses of people who participated in the redemption process.
But to use those addresses, we need to talk to the board.

**Comment by plantether** [comment]
Is it possible to leave a link to to the newsletter or email signup in the Bank to the Future Synereo forum?

**Comment by patrick727** [comment]
@lapin7 I took down the emails and then deleted the comment to Navneets comment. @plantether Is there still activity on that forum?

**Comment by plantether** [comment]
@patrick727 I'm sure people check in from time to time.

**Comment by plantether** [comment]
I don't see any problem with posting something on the Synereo Bitcointalk thread, either, as long as it's not done by an official representative of RChain. Synereo supporters certainly have no problem spamming the RChain ANN thread continually.

**Comment by patrick727** [comment]
Right, what the community members do, so long is at's legal. Is up to them.

**Comment by kitblake** [comment]
@patrick727 I received the newsletter and it looks pretty polished. I've found a few minor errors and a missing link and such. Is the Google doc still the source of the content? Or should I list the problems I find here..

**Comment by kitblake** [comment]
@patrick727 Nevermind, I can see that the content in the newsletter has superseded the content in the gdoc. So here's a list:

Pencilworks has a capital W, as in PencilWorks, Brooklyn
 ...PencilWorks Co-work space

[Ampersands are typically used when the two items are connected, like Mom & Pop, or Q&A.]

Problems with existing Blockchains & RChain’s solutions
Problems with existing blockchains and RChain’s solutions 
[lowercase b, period]

RChain Holdings App Portfolio & Roadmap
RChain Holdings App Portfolio and Roadmap

Ed gives update on Trip to New York and The RChain Holdings Company
Ed gives update on trip to New York and the RChain Holdings company 
[lowercases]

You can view the RChain Holdings’ overview document here
You can view the RChain Holdings’ overview document here. 

Every Wednesday the community joins a hangoug and streams to RChain’s Youtube
Every Wednesday the community joins a hangout and streams to RChain’s Youtube.
[hangout with a t, and a period]

Open source governance is in The RChain Cooperatives ethos.
Open source governance is in the RChain Cooperative's ethos.

Here is an Overview
Following are overviews from the last two sessions.

Bounty programs are currently in the work
Bounty programs are currently in the works

along with more educational content to for the community to engage with.
along with more educational content for the community to engage with.

© Copyright 2017, The RChain Cooperative  12345 Lake City Way NE #2032 Seattle, WA 98125
© Copyright 2017, The RChain Cooperative
12345 Lake City Way NE #2032 Seattle, WA 98125
[since this already breaks onto two lines, might as well make a meaningful break]

Design-wise it looks really good. Especially the images, it's great to see the web house style carried thru in the design. 

There's two problems with the medium gray background:
1. In the logo the word COOPERATIVE almost disappears.
2. In terms of contrast the medium gray is too dark behind the black text. It'll fail an accessibility test.
Can you make it like half as dark?

**Comment by patrick727** [comment]
@kitblake great thanks, i thouhgt I did edit in the google doc first, but maybe as I was tweaking the styling in the newsletter I tweaked the text as well. Moving forward I will continue to try and update the google doc with text first so its easier for these kind of updates thanks to @plantether for that input too.

**Comment by patrick727** [comment]
Just sent it out! Hope i didnt miss any of the edits and it looks good. 

Thanks for the feedback team! @plantether @kitblake @lapin7 !!!

**Comment by plantether** [comment]
@patrick727 I didn't get an email with the newsletter today.

**Comment by kitblake** [comment]
I didn't get the newsletter either, rats. :) 
Now I've subscribed.

**Comment by desaperados** [comment]
I didn't receive a newsletter either :-)

________________________________

**Comment by patrick727** [comment]
@plantether @kitblake @desaperados please subscribe via the form https://forms.sendpulse.com/012a744cdb and then you'll surely receive all of the following ones. 

Right now, its been sent to the people who have subscribed via forms on the RChain websites. 

Cheers

**Comment by lapin7** [comment]
I think this issue has been taken up elsewhere, so I closed it. You may of course reopen it again.
