### ISSUE TITLE
Identity

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#41]
BYOid Trustable Identity Project

SSO with SSI (Single Sign On with Self Sovereign Identity), implementing user controlled universal aggregated identity as the basis for BYOid, using IoP, OpenID, WebID, ethereum uPort, social logins, etc.

Collaborations: RChain.coop, DivvyDAO.org -> diglife.com, giveth.io, cocloud.coop, sovrin.org, movim.eu, solid, consensys, ….

Meeting time: Saturdays 01:00 PM UTC, New York -4, , Seattle -6, Amsterdam +2 
Screen: https://zoom.us/j/6853551826

**Comment by kitblake** [comment]
Thanks for commencing the epic HJ. This project is in an early concept phase. Working on a user story, almost ready for collaborative retelling (aka refactoring, but for stories).

**Comment by kitblake** [comment]
This could be useful, at least for signing in to a blockchain component of a larger infrastructure:
https://hackernoon.com/never-use-passwords-again-with-ethereum-and-metamask-b61c7e409f0d

**Comment by jimscarver** [comment]
today's [byoid meeting log](https://docs.google.com/document/d/1OVUGmxv4q1ywcxDG-V926lrXpkQNDs7n2eO2R5OJdOk/edit#heading=h.e98xkt7b85fy), [video](https://youtu.be/UF5mAPT8KNY)

**Comment by kdvalentine** [comment]
@lapin7 @kitblake 

Would the [Decentralized Identity Foundation](https://decentralized-identity.github.io/) project/consortium be of interest? Makes sense to be aware of the standardization work as it develops. I spoke to the [Consent](http://www.consent.global/) team, interesting work being done.

**Comment by edeykholt** [comment]
@kdvalentine Absolutely.  RChain Holdings will need solutions in both self-sovereign and attestation-based identity, so I'm keenly interested in these topics.

**Comment by kitblake** [comment]
@kdvalentine Thanks, that looks totally on target. 
There's so much momentum in this space that it's hard to keep up with. Whichever project or solution moves to the front, we'll want to integrate with it. Our little, local identity project has to be temporary infrastructure, built with the intention to swap connectors, components, etc. 

[Consent](http://www.consent.global/) looks good too. I see they're in London. And it's "Built on the Ethereum Blockchain.", nice.

**Comment by kitblake** [comment]
Just checked in an initial user story. Here's the rendered version:
https://github.com/rchain/Members/wiki/Identity-Project-user-story
Critique welcome..

**Comment by lapin7** [comment]
I think there's a lot more going on then it seems. The issue is in progress with @jimscarver @kitblake @kdvalentine

**Comment by jimscarver** [comment]
### 2017-12-30

Jim, Gary, Raymond Powell, Kit, Gurinder, Rao

Topics (likely not all items will be completed today - some are future ToDo)

1. Understand Raymond Powell’s (Holochain) requirements, use cases and relationship to DID and Directory service 
    1. Node.js? javascript? 

2. Get Rchain requirements in (Kit Blake?) 
3. Explore funding possibilities, including from Holochain, to meet their requirements 
4. Explore technical architecture rethink based on the above. 
5. Document use cases initially targeted. 
6. DID - Social Ledger mapping document (for different use cases? Different persona?). 
  

Raymond: New Earth collective requirements -- build organically and allow it to emerge.

Temporarily centralized means of authentication - across all projects - OAuth or OpenID based solution. Holochain as true distributed decentralized data layer eventually (both groups agree on the distributed and decentralized). Wants to roll out something in the next week or two - OAuth or OpenID service ? Centralized gateway temporarily is OK as long as distributed decentralized can be implemented over time. Holochain core is developed in Golang, apps in Javascript (or any language eventually). Rchain - ScalaJS.  As a first step, New Earth want to become an IDP so their ID can be used to log into multiple applications used by the members.  Jim says no certified OAuth IDP providers in Javascript?  

Architecture Description: Decentralized identity for an entity, in the control of that entity (how does this work for non-individual entities?) .  Allows users to choose what they require for something to act as them on the network through UMA2.0.  Current OpenID has some centralized service discovery (?) .  OpenID does not enforce that you have trusted ID providers, though most individuals have such.  e.g.Solid.mit.edu HAE of 1 ? etc. can still leverage OpenID. Holochain brings the trustlessness of blockchain into this conversation.  Rebooting the web of trust + IIW (source of OAuth and OpenID) are source of DID. We’re currently not building the full decentralized directory right now but a standards compliant DID directory that can be leveraged in a full decentralized world.

  

Currently we use Mattermost as IDP in our applications, so we need not develop a separate IDP.  solid.mit.edu is a potential IDP to use - it supports webID also?  

Action Item:  Evaluate Express or other node.js based provider for immediate baby step?? Jim thinks there may be good PHP solutions? 

  

Funding:  Holo is asset backed currency = backed by computational and data storage .. They want to stay in sync with that. Fund raiser far exceeded expectations .. $2M available now to $10 M with additional raise.  $25M max. Ico. would be available.  Developer funds may be available. Roll out funding iteration for distributed Distributed decentralized Identity/DPKI is a key initiative in Holochain with funding.

ToDo:  

Schedule weekly peer learning sessions with Raymond and other HC resources on HoloChain development, with initial goal of putting DID directory on Holochain.  

Rao and Gurinder join Holochain channel on MM to read up on Holochain development docs.  DPKI is itself a Holo app on top of HC.  Discovering the public key by itself works only if you are entirely in HC?.  Initial task -- extend DPKI mixin and app(in the sense it has its own set of nodes etc.) to implement DID to make it work with any other decentralized DID structure, including uport (ethereum), RChain etc.  Can we use the DID reference implementation to enable this in whatever is available now?  There are a number of DID implementations that even work off of HTTP.. 

Easy part -- How would some other service authenticate hc id?  

Problem - HC app itself may need to make the calls to various like uport etc.   Would running Solid on HC make sense?  How to make the bridging of various HC apps to DPKI, since it will be most bridged app?

  

### 2017-12-28

Jim, Rao, Gurinder. (continued from noob log

1. Update Architecture document 
2. Basic DID PHP script with unix file backend 
    1. [https://github.com/fire015/flintstone](https://github.com/fire015/flintstone) 
    2. [http://morris.github.io/microdb/](http://morris.github.io/microdb/) 
    3. Update php [https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-centos-7](https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-centos-7) 
    4. [https://firebase.googleblog.com/2017/10/introducing-cloud-firestore.html](https://firebase.googleblog.com/2017/10/introducing-cloud-firestore.html) 
    5. [https://firebase.google.com/docs/auth/](https://firebase.google.com/docs/auth/) 
    6. [https://firebase.google.com/docs/firestore/data-model](https://firebase.google.com/docs/firestore/data-model) 
    7. [https://github.com/firebase/snippets-web/blob/master/firestore/test.firestore.js#L154-L155](https://github.com/firebase/snippets-web/blob/master/firestore/test.firestore.js#L154-L155) 
    8. [https://github.com/GoogleCloudPlatform/google-cloud-php-firestore](https://github.com/GoogleCloudPlatform/google-cloud-php-firestore) 
    9. [https://github.com/googlecloudplatform/google-cloud-php](https://github.com/googlecloudplatform/google-cloud-php) 
    10. [https://github.com/firebase/snippets-web/tree/master/firestore](https://github.com/firebase/snippets-web/tree/master/firestore) 

3. PHP OAUTH login to mattermost 

### Saturday Open Meeting 2017-12-23

Rao, Jim, Gurinder

Add topics anywhere is list:

1. Frustrations, excitements and/or meeting expectations round 
    1. Rao: get up to speed on current thinking, components 
    2. Gurinder: wanting time to get things started,  
    3. Jim: Great +ve: Art Brock took guide role in holochain DKPI - identity channel 

2. Complete rchain membership for funding. Join diglife and holochain  for cooperation 
3. [Architecture diagram](https://docs.google.com/drawings/d/1hegtwlU1YZn21RT5hKOOBHVKwiHDn6HYwO4ykSXxQAE/edit) 
    1. Subutai 
    2. Cloudron on top of Subutai? When? How? Who? -- John Grant, Jochim, jim w ? 
    4. Initially BYOID should allow access to Social Ledger domain in Chat.divvydao.net, rchain.divvychain.net (to be moved to its own), chat.holochain.net, chat.letssystem.com (direct spin-off from Digitallife collective -- developing token exchange?) 
    5. Bridges between channels share activities across channels. 
    6. BYOID supports Social Ledger 
    7. Distributed OAUTH draft proposal from Amazon [https://tools.ietf.org/id/draft-hardt-distributed-oauth-00.html](https://tools.ietf.org/id/draft-hardt-distributed-oauth-00.html)  may be relevant as an implementation model. 

4. Know yourself 
5. Review of last week's topics 

### Saturday 2017-12-16

Gary, Jim, Tristen Roberts, 

1. Holochain/rchain/social ledger identity,  
2. Tristen setting up meeting with christopher allen and others will report in holochain DPKI channel 
3. Planning oauth for social ledger 
4. No video today 

### Saturday 2017-12-09

Jim, Gary, Kit, MZZ, bot

  

1. Oauth integration universal SL SSO 
    1. Store tokens in cookies and oauth cache oe firebase encrypted 
    2. Ledger webhook landing page per MM server. 
    3. discord/telegram oauth 

2. /dig id UMA2.0 functionality 
3. Holochain identity 
    1. [App: DPKI-Identity](https://chat.holochain.net/appsup/channels/app-dpki-identity#) channel ([holo team invite](https://chat.holochain.net/signup_user_complete/?id=uc7j4tp8jbga78nw363gbgqdxc)), [github](https://github.com/Holochain/dpki) 
    2. [The Agent-Centric Web of Trust](https://docs.google.com/document/d/1DUBkvZZsbjM2T6wGNpxGluzPZlK8QP4wyQXInAdWBLU/edit#heading=h.mfu7d5wcpolc) 
    3. DID DNS on holochain. 
        1. Dependant on Anchor GET functionality. 

### Thursday 2017-12-07

Leah, jim

  

Know yourself planning, BYOID team  vs. RChain identity channel.

### Wednesday 2017-12-06

- Holochain sprint bridge? 
    - Id coop on DID directory 
    - John in chat: fernanda from village lab will also connect online. at 3.30 or 4 (GMT) webinar engagement would be great  

- Oauth aggregation 
- Metamaps authentication 
- /dig id 

### Saturday 2017-12-02 

Jim, kit, gary, John Kellas, MZZ

- A prerequisite is a distributed identifier directory[https://w3c-ccg.github.io/did-spec/](https://w3c-ccg.github.io/did-spec/) which is not specific to the social ledger, holochain or rchain etc. DNS of DIDs 
    - Firebase /dig 
    - Holochain 
    - Decentralized DNS 
    - PGP key directories 
    - uPort 
    - Other? 

- John kellas - [https://visual.tools](https://visual.tools)/  
- Holochain cooperation on the social ledger and metamaps,  
- Oath aggregation, 1st mattermost. 
- Scribe, /dig team in BYOID? 
- What is exposed is part of the social ledger and everything on the social ledger is part of your identity and reputation. 
-  we can control our identities on every level everywhere that we might control the destiny of our personna in our associations  
Hubot [https://hubot.github.com/](https://hubot.github.com/)

**Comment by 9rb** [comment]
See above notes from Jimscarver.  We're using this item for reporting work on Bring Your Own ID and related Identity efforts.  To provide single sign on for the Coop and design self sovereign identity to be put on RChain for the Coop membership.

**Comment by drbloom** [comment]
@9rb - Co-op membership requires upload of a valid Government Issued photo ID to [https://member.rchain.coop](https://member.rchain.coop) followed by a live (webcam) verification.

**Comment by lapin7** [comment]
Continues with [#254](https://github.com/rchain/Members/issues/254)
