### ISSUE TITLE
O> Channel Etiquette & Guidelines

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#42]
Hello Friends, 

Let's get some feedback on this document, I know that censorship is a touchy subject so i'm sure we all have strong input. 

I believe growth takes clarity and guidelines help to provide some direction toward the clear goals. 

https://docs.google.com/document/d/19nK5-ymKSzGV9sd7dtb5TaCdkWXO-u3Iaak4JpTBgJI/edit?usp=sharing

What do you think?

**Comment by kitblake** [comment]
Patrick, et al, I know time and thought went into that doc but I think it's a bad idea. It means the trolls are succeeding.

Trolls intend to disrupt, create chaos, ferment dissent against the community order, and prevent consensus. This doc and especially any followup actions will trigger divisions in the community.

It's not like they'll go away, they'll just operate on the edge of the new parameters.

Ignore the trolls. Don't reply, don't engage, just carry on. That's the only way to render them ineffective.

**Comment by patrick727** [comment]
@kitblake that's good feedback. 

This document was a request.

There are certain community examples of highly productive projects where guidelines do work. 

It's about every community tool having a clear purpose and that purpose being stated so that the community can hold each other accountable. 

It's not going to get rid of all the trolls, but it sets the stage for what the slack, as a tool, is for.

I believe that another good tactic is to directly confront specific profiles and get them into a video call, or one of the hangouts because they will humanize the people involved instead of acting like everything is done by robots.

**Comment by kitblake** [comment]
Every year there's a EuroPython conference in a different country in Europe. Around five years ago they had problems with behavior and created this Code of Conduct. It's a nice example:
https://ep2017.europython.eu/en/coc/

**Comment by lapin7** [comment]
In order to keep discussions fruitful at Slack, we can only promote RChain's mission and values. We cannot screen content or ban people (even if they are trolls). It's best to neglect what's bad. Rules are for Fools. It doesn't work.

On top of that screening or moderating creates a hierarchy. Controllers and controlled. Official tongue and what else? That's not the way I prefer. So let's be keen on RChain's mission and values. 

**Mission**

The RChain Cooperative mission is to build a decentralized, economically sustainable public compute infrastructure.The platform boasts a modular, end-to-end design that commits to correct-by-construction software and industrial extensibility. It’s multi year undertaking and involves many different part of software components.

**Values**

The cooperative attracts members that share the mission and the values of the cooperative:
● We make decisions. Decisions have to be supported at least three members.
● We are courageous. We are allowed to do the wrong thing, because otherwise, we can never do
the right thing either.
● We share profits according to SMART participation in results.
● We advance one another. We depend on our cohesion.
● We trust one another. We know that each and every one of us wants the best for the cooperative.
● We take initiatives and respect those of others.If we see something we dislike, we respond by
making and spreading something we like, instead of pointing out what we dislike. We need
diversity in our activism and strive for it.
● We respect knowledge. In discussing a subject, any subject, hard measured data is preferable.
Second preference goes to a person with experience in the subject.
● We respect the time of others and the focus of the organization.
● We act with dignity. We’re always showing respect in our shaping of public opinion: respect
toward each other, toward newcomers, and toward our adversaries.
● We are long term.

**Style**
The cooperative has to be managed in a way that the members believe in what they think is best for the reaching the mission.

**Comment by patrick727** [comment]
@lapin7 @kitblake what are you thoughts on this situation. 

The slack becomes full of unproductive noise and the people that are actually producing for the project don't engage on it anymore, or far less. 

Its been directly expressed in hangouts by greg and others that they will simply engage less, which kind of defeats the purpose of the slack in general. 

I think these types of judgement calls are important because what would you rather have? 

A fully open and inclusive community where anything goes, but non of the key influencers participate in?
or a directed community channel used as a tool to increase production of the community goals?

**Comment by kitblake** [comment]
Dealing with community in the early days of an initiative is a delicate task. You have to let the community form itself. Because:

> Community happens, or it doesn't. You can't force it to happen.

We really want a community to develop. It's critical for the success of the venture! So we don't want to establish a structure of core players (who might be getting paid) that are centrally controlling spaces that people expect to be open and communal. 

I'm in multiple Slacks. Here's a report from one of them:
 "Your team sent a total of 3,529 messages last week. Of those, 13% were
  in public channels and 87% were direct messages."
Regardless of the content of the public channels, it's working as a connection tool. And that particular community is policing itself. That's what we want. 

I see Slack as the corner bar. It's good for quick questions, polls of interest, and short discussions. But it's not a place where any real work gets done. It's hard to concentrate and even if you take a table with some friends, some inebriated noob can always join in and dilute the signal level. Fine, time to leave the bar and go to Cafe Github. 

"The people that are actually producing" need to be reachable and chime in on pertinent discussions. One can call them with @username and they should participate. But if it's a troll being deliberately annoying you ignore it. 

Again, what I see happening is the trolls succeeding. Disregard their antics, don't engage, and let the community organically develop.

**Comment by drbloom** [comment]
Moderating a _free_ Slack such as Ourchain is not feasible. The management tools are too limited. I suggest we maintain Ourchain Slack with minor changes.

- Limit posting in #announcements channel to Team Owners and Admins
- Consider making some channels Private
- Consider alternative platforms, including *self-hosted* platforms

If everyone wants it, I am willing to host and administer another platform such as _Rocket Chat_. Self hosting enables much more control, but requires that someone be trusted  and responsible to both the board and to legal authorities.

Does anyone know of a good enough federated solution? Members should have the choice of subscribing to a node or running their own. I like mastodon/GNU social/OStatus but these are still a bit buggy.

**Comment by patrick727** [comment]
@kitblake @lapin7 great points. I like @drbloom's proposed solutions as well. 

What do you guys think?

**Comment by patrick727** [comment]
Is it fair to counter the current "Guidelines+ Etiquette " with this proposal

-Limit posting in #announcements channel to Team Owners and Admins
-Consider making some channels Private (tbd)
-Consider alternative platforms, including self-hosted platforms (jim's suggested mattermost)

- create anonymous feedback form

**Comment by kirkwood** [comment]
@drbloom has articulated it better than I could, but I think his proposal is probably the only thing likely to work. However, I would go one further and argue against _free_ Slack as a private communications mechanism, though it works well for communication to and with a wider audience. Unless you pay for it, Slack is just too hamstrung.

I don't have better suggestions than the standard, monotonically increasing in complexity set of
 * pay for team Slack; or,
 * use Google tools; or,
 * try Rocket chat (which looks pretty neat); or, 
 * run a private IRC server on AWS or similar; or,
 * _etc_.

**Comment by kitblake** [comment]
IMHO you guys (@drbloom and @patrick727 and @kirkwood) are on target. I'll submit a couple of patches:

I'm not elite enough to be in any private Slack channels, so I don't know if users can see or know that private channels exist. If so, I'd be against the idea. Sort of like a private club with doorman at the back of the bar. 

Slack is pretty ubiquitous among crypto initiative communities so it would be good to give it some more time. Setting up another chat server/app that's members-only sounds fine. Let's see if we like it better. Or we just use Telegram [partially joking].

(Also a 'local'/cloud installation could overlap with an up and coming identity project where we'll need something in which to login to with our own doorman.)

**Comment by lapin7** [comment]
I agree with @kitblake. Leave Slack as it is. Avoid private channels. And promote github as our work area.
BTW @drbloom raised the question about where to place those guidelines.

@patrick727  - Where in :slack:Slack would you post _Guidelines and Etiquette_ ?
Moderating a _free_ :slack:Slack such as Ourchain is not feasible. The management tools are too limited. I suggest keeping the current setup and:

- Limit posting in #announcements channel to Team Owners and Admins
- Consider making some channels Private
- Consider alternative platforms, including *self-hosted* platforms

If everyone wants it, I am willing to host and administer another platform such as _Rocket Chat_. Self hosting enables much more control, but requires that someone be trusted  and responsible to both the board and to legal authorities.

Does anyone know of a good enough federated solution? Members should have the choice of subscribing to a node or running their own. I like mastodon/GNU social/OStatus but these are still a bit buggy.

**Comment by patrick727** [comment]
@lapin7 @drbloom @kitblake a potential solution to "where to post guidelines" especially considering Greg's feedback in the latest hangout would be to generalize the guidelines to "communication channels guidelines" and post it as a link in the github references.

That way its still there to reference if there is a spectacular troll, but at the same time its non-offensive to a regular crowd.

**Comment by jimscarver** [comment]
At the activist meeting today it was decided to experiment with the use of mattermost as a replacement for most or all of the activity here in slack and ultimately integration with governance and task rewards.  Please participate in the test at https://rchain.divvydao.net/signup_user_complete/?id=x37h6j8iotgpzkrs9ysksjc8cc to join the community team. I also added teams for staff and activists which are by invitation only. Anyone can join community.

**Comment by patrick727** [comment]
@drbloom @kitblake here we are! 

So based on the convo we just had we are looking to 

Draft up descriptions ofr each channel that include references and etiqutee
Draft up copy for invite page that includes "click" that you have confirmed that you have read that etiquette guidelines

**Comment by kitblake** [comment]
Just updated the Slack Etiquette doc with some minor fixes. It's in /reference but not yet listed in the README.md. @patrick727 I assume you'll fix that with your renovation there. 

Shall we collect/collate/collaborate on the channel descriptions in one doc? 

How's this for the invite page:  
> RChain has a [Code of Conduct](https://github.com/rchain/reference/blob/master/RChainSlackEtiquetteGuidelines.md) for Slack. While we don't expect you to actually read the doc, we do ask you to acknowledge that it exists. (You can find it later on [Github](https://github.com/rchain/reference/).)

**Comment by kitblake** [comment]
For the Slack channel descriptions I've added a sheet to Patrick's "RChain - Linkbuilding Spreadsheet" that provides an overview:
https://docs.google.com/spreadsheets/d/1NaZbj4rjAI2-PjUJLpXGglCkvtIQc9iBTWfa2AU8oFI/edit#gid=809538338
The same link was shared in yesterday's Activist meeting. 

Happily someone cleaned up the channels and deleted all the flaky ones! And fortunately this happened just before I spent time extracting the channel names and descriptions. 

In the sheet we have these columns: 
- current channel name
- new channel name
- current description
- new description

The names and descriptions are all current and – lo & behold – we have descriptions for all channels now. Maybe whoever deleted the flaky channels also added descriptions? 

In any case, I'm not sure if I should take this further. I could flesh out some of them. But maybe other people want to add their 2 Gregs..
[Bitcoin has Satoshis, RChain has Gregs]

**Comment by patrick727** [comment]
@kitblake i actually cant edit in reference's that would have to be ian or ed I believe. 
This is great, 

Although I believe this should be in a separate document because it doesn't have to do with link building specifically, thank you and I will propose some new descriptions.

**Comment by patrick727** [comment]
went ahead and proposed a bunch of descriptions. we can definitely expand on them with document links, and also the dev, or leader that best relates to that channel(if we deem this beneficial, it may just backfire and result in spammage)

**Comment by kitblake** [comment]
Nice work. The descriptions are all consistent with a congenial tone. 

We'll have to test putting markup in the texts. 

Good idea to have someone responsible for each channel, as in they're the contact and the go-to person for channel changes. For now we could default to the channel creator.

**Comment by patrick727** [comment]
There is a need to reiterate this issue for

discord
reddit
telegram

**Comment by jbassiri** [comment]
What worked and didnt work about Slack etiquette & guidelines? It didn't seem widely effective. Rule breakers will break rules anyway. 

Our best tool in terms of etiquette is culture. Our culture of transparency, accountability, and open dialogue speaks for itself and brings people into the fold. 

-- 
Jacob Bassiri-Tehrani
(516) 458-7439

**Comment by patrick727** [comment]
@jbassiri I agree about pushing the culture. 

The etiquette came at a time where we were shifting gears anyway. 
The guidelines are also for people running channels/meetups as an added layer of accountability

**Comment by kitblake** [comment]
@patrick727 You could rename this issue "Channel Etiquette & Guidelines". Or close it. 
For Telegram we're keeping the rules in code (it supports Markdown):
https://github.com/rchain/Members/blob/master/projects/bots/groupbutler/rules.md

**Comment by patrick727** [comment]
Thanks @kitblake I did just.

Great job with telegram

**Comment by kitblake** [comment]
@jbassiri I agree about pushing the culture too

**Comment by dckc** [comment]
It looks like https://github.com/rchain/reference/blob/master/RChainSocialMediaEtiquetteGuidelines.md is what we ended up with.
