### ISSUE TITLE
Newsletter Drafting - July 15th

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#61]
The last newsletter went out. Got some last minute feedback on the design and content. 

Proposed bounty for help to @plantether, @entropee, and @jimscarver for feedback. 

here is the doc for the next draft the goal for this one will be to send test emails out 7/13 and the campaign out on 7/15 might end up being 7/16 because of the hangout on 12th. 

https://docs.google.com/document/d/1Lfs9xbq9hx3nZqLab5Dk4StgoPCOdsT4WJ0OShTEd6A/edit#

**Comment by kitblake** [comment]
Content looks good. Check the capital usage:
- "The Casper Test Framework" should be caps in the white heading too.
- GO should be Go.
- "...updates on Holdings company."
- Do a Search & Replace for Slack, Github, YouTube, Mattermost.
- Github/Rchain/Members is actually rchain/Members (but the link works).

Also:
- "Greg's proposal" with possessive. 
- "Greg closes with discussion" (missing s)

How about, instead of:
"It may not be perfect, but is worth engaging with."
"It may not be perfect, but we're working on it."

**Comment by patrick727** [comment]
Great feedback Kit! Will make changes
