### ISSUE TITLE
Newsletter Drafting - August 1st

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#62]
here is the doc for the new newsletter to be published early August. 

https://docs.google.com/document/d/1OYy47xwRt4IqdsUqihDDVgz7bTIa8R3vepgvucpzpJQ/edit#heading=h.6rfhnpgpo0ep

**Comment by kitblake** [comment]
Checking the newsletter while Bitcoin splits ;-) 
All minor fixes, otherwise looking good!

“Out of many, one” is the Motto...
“Out of many, one” was the motto... [lower case m, maybe 'was the motto']

Verzion 2.0
Version

the one “chain” is really formed out the the many
the one “chain” is really formed out of the many

namespaces that will act Autonomously
namespaces that will act autonomously [lower case a]

Speaking of "for the good of all"... [typewriter quotes]
Speaking of “for the good of all”... [these are smart quotes]

Earlier this month we witness’d
Earlier this month we witnessed

95% of the bitcoin activated the Segwit fork
95% of the Bitcoin miners activated the Segwit fork.

...of the communities formed around these projects a true inspiration.
...of the communities formed around these projects is a true inspiration.

...patches(as noble, and frankly cool to talk about, as they have been)
...patches (as noble, and frankly cool to talk about, as they have been).
[space and period]

...a better idea of how The RChain Cooperative and Holdings Company
[this reads like it's one entity]
...a better idea of how the RChain Cooperative and the Holdings Company

...that have trillions of dollars, and personal information to protect.
...that have trillions of dollars and personal information to protect.

Every Wednesday the team joins in a hangout [/break]
Every Wednesday the team joins in a hangout that streams...

Working on a new whitepaper, e pluribus unum 2.0 
Working on a new whitepaper, E Pluribus Unum 2.0 [caps]

This newsletter is sent to you, because you are a customer or subscriber of RChain The RChain Cooperative.
This newsletter is sent to you, because you are a customer or subscriber of the RChain Cooperative
