### ISSUE TITLE
RChain Community Reward Program

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#78]
@kdvalentine has put together a draft for a [community reward program](https://docs.google.com/document/d/18-U01CQ018TebKxxHq9yCgYBAzOI0bewx7OgSjzEVH4/edit#heading=h.kry0vwbolfdq) for activist engagement and in particular content curation. 

The finalization of this will be dependent on full budget write up, but we can begin to outline some of the tasks, and flow for consensus on the topics, so please help us with feedback and experimentation. 

The way the newsletters, and now the Wikipedia document has been coming together this can be really impactful, we will still need to figure out how to measure contributions and Jim has some good examples of decision making matrix's that might be of use, also Kevin had mentioned that district uses slack consensus. We can also vote through the meetups with surveys, i tend to like the most live option because the true activists are the ones engaging in the github, slack, and hangouts.

**Comment by kitblake** [comment]
Did some minor cleanup and editing on @kdvalentine's doc, then started thinking about larger issues. I put in a comment, which is now deleted, moving it to here:
> What is the public destination of this doc, i.e. where would it be published?

The language seems directed towards an external public, as opposed to insiders. The text is also effective onboarding material so we can make use of it. 

As for getting people motivated – and thus onboard – we need to have tasks and projects published somewhere. If the bounties per item are not decided yet that shouldn't hold us up. We could start in a spreadsheet. 

I know that @patrick727  has a "RChain Content & Links" spreadsheet that's specifically for marketing stuff. We could do something similar that serves as a general list of all available tasks and needs. 

The generic ones that @kdvalentine defined should be in there, as well as specific tasks people have (e.g. I would like someone to write an Entrybot, a really simple script that reacts when people join Slack). If we have such an overview that would help get the RChain Activist Reward Program rolling..

**Comment by patrick727** [comment]
@kitblake yes this would be a great thing to start on, that spreadsheet. Also if @Jake-Gillberg's voting mechanism works for git issues then is it possible to use that as a means of assigning bounties? 

I've been told to come up with a marketing budget and proposal, I think we should do the same for community building and governance. 

Overall this is coming along well and may work that after co-op registration is open this can be a membership type of program

**Comment by kdvalentine** [comment]
# **RChain Activist Reward Program**

## **Earn RChain Tokens for your participation in growing our community**

As an Activist of the RChain Cooperative you are invited to propose projects which contribute to the platform's development, its governance, and the decentralized community as a whole.

We would like to thank everyone who has given us feedback on the [Platform Architecture](http://rchain-architecture.readthedocs.io/en/latest/) document. In an effort to increase community engagement as well as reward Activists for their contributions to the RChain Project, we will be allocating 1,000,000 [RHOC](https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5) tokens for this purpose. The RHOC is an ERC-20 token on the Ethereum network that will be redeemable for RChain's network token (REV) when launched.

### **What is RChain?**

[RChain](https://district0x.io/) is a scalable, high-performant, decentralized, censorship-resistant, general computation platform for building secure applications which aims to address a variety of social, political, and economic problems.

The RChain Co-op intends to enable new means of group coordination through economic incentives, disintermediating marketplaces and creating a wider distribution of economic incentives to its members. 

Our mission is to empower all citizens of the internet with the tools to build and control the platforms they frequent daily, affording them the opportunity to participate in the financial successes of these services.

### **Activist Reward Program Details**

In these early stages, it is imperative that we collect your feedback and explore the many ways that you envision making use of the platform. The ultimate utility of the network will be driven by the diversity of ideas and developers it can attract.

**How can I earn RHOC?**

[Co-op member 1 & 2] will subjectively reward feedback, thoughtful discussion, and other contributions made to the RChain Project. 

Some ideas include: Contributing directly to our [codebase](https://github.com/rchain), creating a [video](https://youtu.be/Qftq9S34xgg) or writing an article about RChain on your personal blog or [Medium](https://blog.coinfund.io/an-introduction-to-rchain-d5fe303e9fe1), inviting your friends to our Slack, educating others on what RChain is, following us on [Twitter](https://twitter.com/rchain_coop), posting about RChain on social media, helping us out with translations, or contributing to our Wiki or [Documentation](https://rchain-architecture.readthedocs.io/en/latest/). 

We've setup a bot in our #community [Slack](http://slack.rchain.coop/) channel, that allows you to post your proof, and if 5 or more other community members give you a heart emoji reaction you will get a :RHOC: emoji reaction and your RHOC reward. Each submission that receives 5 heart emojis will be reviewed so the system is not game-able. These rewards can be tracked[ here](https://docs.google.com/spreadsheets/d/1c9LJ_NjbsqJFqgR9FcVbnXIWyXoSw2_CSUuALsuoEJ4/edit?usp=sharing).

**Join the Movement**
If you believe in RChain's vision of a decentralized computing platform for the benefit of all global citizens, come join us in building the future together and participate in this exciting journey.

**Comment by kdvalentine** [comment]
@kitblake Moving the document here per your comments. Let's update this document in sync with the other issues you mentioned that will impact this document.

**Comment by lapin7** [comment]
I've changed the gsheet of Jim "[RChain Activist RHOC Distribution](https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit#gid=1970624799)"


In Tab "Budget voting" all the Github issues are listed. The goal is to assign USD to those issues and to clean it up. I've set up a voters list that maybe incomplete or not correct. So you can modify the list as you want. The voters are invited to fill out USD amounts per issue.

From Budget voting follows Budget Allocation. After that a P2P approval sheet has to be set up for Budget Exhausting, i.e. transferring rewards to Activists.
In the coming days the whole system has to be fleshed out. 
You're most welcome to help.

**Comment by kitblake** [comment]
For clarity's sake (because I didn't get it at first) in the "RHOC rewards August 2017" sheet the columns per individual work the same as in the "Budget Allocation" sheet: i.e. the percentages that we fill in get averaged.
So both the Budget Allocations **\*and\*** the RHOC Rewards are an average of what your peers say.
This works nicely. We all guesstimate a budget, then when the project concludes the team members collectively estimate their participation, and that determines the payout.

**Comment by lapin7** [comment]
The GitHub voting button serves as setting the priority of an Issue (urgent, important, impact)
The budget allocation is another thing. It goes through the Gsheet. A completely decentralised system based on trust, normal behaviour, weak consensus, peer control.

**Comment by lapin7** [comment]
Some thoughts about [RChain Activist RHOC Distribution](https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit#gid=846811289):

- All issues need to have a budget allocated. At the moment some known Activists express what's needed in USD to solve an issue. A rough estimate is the number of hours that you think is needed. And multiply that with an hour rate of $40. I made a start with some issues, but by copying and pasting you can add more issues and invite Activist to give their estimate. Probably the number of known Activist needs to be extended.
- Activists get only a reward when they are a collaborator on Github\Member
- However people can be incentivised by receiving small amounts if they've done some work.
- Everybody who does something on an issue needs a row under a certain issue in tab "RHOC rewards August 2017". So that includes Activists who have an SoW with a monthly payment. For example: HJ (lapin7), Patrick727, JimScarver, ....
- Like that we can get later an overview on which issues the RHOC are spent
- It's not clear yet who can give estimates of what Activists have been doing on certain issues. We just start with some known Activists. And later that can be changed.
- At the moment there's a budget of 100,000 RHOC for expenses that we agree on in a decentralised fashion. This means that there's no further approval needed from the Board.
- The expenses on SoW's probably need still approval of our Kenny Rowe (COO) or Greg. However Greg is sending chunks of 1 mln RHOC to a wallet that HJ manages. Find [here] (https://etherscan.io/address/0x8b629a47c3c633dadc47d6f0d6f66882593817f3#tokentxns) 
 the total budget
- For invoicing purpose, the Activists add the issue nrs. that they've been working on
- The way of invoicing becomes more clear in a few days

**Comment by lapin7** [comment]
@kdvalentine (especially)
Please review [RChain Community Reward Program](https://docs.google.com/document/d/18-U01CQ018TebKxxHq9yCgYBAzOI0bewx7OgSjzEVH4/edit#), because I suggest to send it out ASAP to all the Activists that are listed in our [Google Group](https://groups.google.com/forum/#!members/rchain).

**Comment by lapin7** [comment]
Please replace "Activist" with "Member"

**Comment by dckc** [comment]
I'd like to use this issue to stand for the original establishment of the bounty "contract" in Aug 2017.

 - See also: README/CONTRIBUTING update 69d02c4 Sep 18
 - [Welcome to the Bounty Program](https://github.com/rchain/bounties/wiki/Welcome-to-the-Bounty-Program)
