### ISSUE TITLE
M> Hangout Summaries - Github page

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#79]
M> Indicates that this is a project within the "Marketing" category

Goal:

It will be helpful if there is a github page, like the FAQ(even better in markdown) with summaries of the latest hangouts that include links to the timestamps. 

[Here is a google doc](https://docs.google.com/document/d/16GsJaP9K8M1MUFaXeK4jzVjxjihkE4VMkmaQ5pigrzQ/edit#) that I used to write notes, we can start with august moving forward if someone is willing to pick this up.

**Comment by entropee** [comment]
Anyone interested in working on this I think this should be rolled into a video production project. I have started a channel called #Video Channel Coop in the Diglife DivvyDao Mattermost domain, here: https://chat.divvydao.net/divvydao/channels/video-production-coop. I can provide invites if you need them.

**Comment by entropee** [comment]
Can this issue serve as the video production one, or should I start a new one?

**Comment by patrick727** [comment]
@entropee i'd start a new one. I was looking for timestamped summaries of the hangouts for peoples reference currently I have had to do all of them manually for the newsletters.

**Comment by dckc** [comment]
I'm interested to pick this up -- at least to migrate the existing summaries to markdown. Those summaries in the newsletters are a gold-mine.

**Comment by dckc** [comment]
I converted a big chunk of the links from the newsletter archive to markdown: https://github.com/rchain/Members/wiki/Weekly-Update-Index

**Comment by dckc** [comment]
These things have lots of names: hangouts, community updates... I think I've seem them called zooms? I went with Weekly Update. does that work?

**Comment by lapin7** [comment]
@dckc 
Does this budget have to be increased?
Are the rewards distributed? 
Please use form [Budget allocation and - spending](https://docs.google.com/forms/d/e/1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA/viewform)

79 | https://github.com/rchain/Members/issues/79 | In progress | Hangout Summaries - Github page | Marketing | 3 | $ 400.00 | $ - | $ 400.00 | $ 400.00 | ⍴ 4,000.00 | @kitblake @lapin7 @patrick727
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by patrick727** [comment]
@dckc again great work on this!

The video description is "RChain Debrief" so we will use that moving forward, zoom is the software to hold the video conferences. 

Id like to see this page a bit more detailed then the newsletter verzions moving forward, perhaps @plantether can help with this. 

see https://docs.google.com/document/d/1Va_u-I_IWCvpWVgQXNKsFuhpaH-enouhPotJMTGoiRM/edit?usp=sharing

**Comment by plantether** [comment]
@patrick727 @entropee @dckc @kitblake What do you think the more detailed format should be? More and more detailed summary lines, more summary lines but shorter, existing summary lines but annotated?

For example, for Sept. 6:
The newsletter summary line is:
```- Technical Discussions: Q&A on Namespaces from Discord```

Do you prefer:
(A) Breaking it down into more and more detailed links like the following:

[Technical Discussions: Q&A on Namespaces from Discord](https://youtu.be/vKD4AjoUVxE?t=7m58s)
- [How users and contracts interact with each other through channels, and the relationship among users, contracts, namespaces, channels, and nodes](https://youtu.be/vKD4AjoUVxE?t=524)
- [The way validation of transactions will work so there can be concurrency and determinism at the same time](https://youtu.be/vKD4AjoUVxE?t=930)
- [Questions and clarifications about validator pools, how namespaces allow communication with other blockchains, and the economic incentives for validators](https://www.youtube.com/watch?v=vKD4AjoUVxE&feature=youtu.be&t=930)
- [How a node filters out transactions it will participate in based on whether the transaction requirements match the node’s declared capacities](https://youtu.be/vKD4AjoUVxE?t=1597) 

OR

(B) More links, but with descriptions that are not as detailed:

[Technical Discussions: Q&A on Namespaces from Discord](https://youtu.be/vKD4AjoUVxE?t=7m58s)
- [How users and contracts interact with each other through channels](https://youtu.be/vKD4AjoUVxE?t=524)
- [The way validation of transactions will work](https://youtu.be/vKD4AjoUVxE?t=930)
- [Questions and clarifications about validation and namespaces](https://www.youtube.com/watch?v=vKD4AjoUVxE&feature=youtu.be&t=930)
- [How a node filters out transactions it will participate in](https://youtu.be/vKD4AjoUVxE?t=1597) 

OR

(C) The same links used in the newsletter, but with linked (or unlinked) annotations that are longer or shorter, more or fewer?

OR 

(D) Something else

**Comment by dckc** [comment]
I very much like the idea of elaborated summaries of the videos, but I wouldn't add them to the same index. The current list of 5 to 7 links per week was just what I, as a new person, needed: it was the difference between

 - _yikes! 40 weeks of updates! I'll never find time to watch them all. And how will I keep track of which is which?_
to
 -  _ah. OK... now I can pick and choose which ones to watch, whether for the first time or coming back again._

This index is most useful if it's _all on one page_ and not one that makes my scrollbar tiny.

The next level of elaboration that's useful is capturing the main points in a way that pretty much substitutes for watching the video. Just like this bit of the doc you cited:

> Private sale: Going well, over 4.4M has been closed out and several more coming in, including several large funds coming in. 

It's very valuable to attribute such points to who made them. Points like "People really interested to know we can talk about that off line." are pretty much useless without knowing who said it.

Paraphrasing in text carries a real risk of not quite getting it right; i.e. putting words in somebody's mouth that they didn't say. If the text description isn't visible to the participants in near-real time, then it may be important to review them after the fact, which is somewhat labor intensive.

**Comment by dckc** [comment]
Thanks @patrick727 ; I made an edit to use "RChain Community Debrief" (more) consistently and add serial numbers and renamed it to https://github.com/rchain/Members/wiki/Weekly-Debrief-Index

**Comment by patrick727** [comment]
@plantether I agree with @dckc 's points, so if i had to choose something like B would be my choice but considering the lenghtyiness. 

@edeykholt made the same comment in our meeting yesterday In regards to this issue as well as the Wiki issue which go hand in hand. "Less like a complete transcript, and more like a clean primer"

**Comment by lapin7** [comment]
Great @dckc has assigned himself a reward for this issue and a budget was already allocated. It would be nice if @dckc also set's a percentage for the work that @patrick727 , @entropee and @plantether have done.
He also needs 2 more collaborators to vote as well on the rewards. 

And @dckc could still assign a budget to this issue, according to his opinion. This however not needed, because there are already 3 persons who have set a budget already.

**Budget allocation**

URL | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | Voters |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/79 | In progress | Hangout Summaries - Github page | Marketing | 3 | $ - | $ - | $ 400.00 | @kitblake @lapin7 @patrick727 |  

**Budget spending**

URL | Description | Category | Set | Set | ⍴ To Pay | Activist | AVG work | Votes | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/79 | Hangout Summaries - Github page | Marketing | 3 | In progress | ⍴ - | @patrick727 | 0% | 0 |  
https://github.com/rchain/Members/issues/79 | Hangout Summaries - Github page | Marketing | 3 | In progress | ⍴ 1,200 | @dckc | 30% | 1 | @dckc 0.3
https://github.com/rchain/Members/issues/79 | Hangout Summaries - Github page | Marketing | 3 | In progress | ⍴ - | @entropee | 0% | 0 |  
https://github.com/rchain/Members/issues/79 | Hangout Summaries - Github page | Marketing | 3 | In progress | ⍴ - | @plantether | 0% | 0 |

**Comment by dckc** [comment]
Thanks, @patrick727 !!

**Comment by patrick727** [comment]
the index is up to date again guys! added the past two hangouts

**Comment by patrick727** [comment]
@drbloom will you please add this summary index to the /reference page. I believe it belongs there and the FAQ. I did a pull request for the FAQ but couldn't figure it out for the /reference page. 

https://github.com/rchain/Members/wiki/Weekly-Debrief-Index

**Comment by drbloom** [comment]
@patrick727 - I don't think it belongs there because the rchain/reference README currently makes no mention of Co-op membership, newsletters, hangouts, projects, etc. 
> ## Co-op

> - [FAQ](https://github.com/rchain/reference/blob/master/faq.md)
> - [About Cooperatives](http://www.prout.org/pna/cooperatives.html)
> - [Articles of Incorporation, Bylaws, and board minutes](https://github.com/rchain/board)
> - [Other legal documents](https://github.com/rchain/legaldocs)

What do you think about adding the item **Membership** to the above, linking to the README for rchain/Members? A link to the summary index **Weekly-Debrief-Index** is already included there.

 rchain/reference > Membership > Weekly-Debrief-Index
