### ISSUE TITLE
Proposal: Slack Invitation Page to require RHOC

### ISSUE THREAD

**Issue by drbloom** [rchain/Members#82]
In an effort to discourage trolling, our friends at Gnosis have begun requiring their Slack users to hold GNO. This is accomplished by updating the process by which new Slack users are on-boarded.

Gnosis modified the same "invitation server" that RChain is using, to look up an ERC20 token balance with MetaMask. The code is open-source on GitHub, and compatible with RHOC.

Here is the invitation server at [https://slack.gnosis.pm/](https://slack.gnosis.pm/)
<p align="center"> 
<img src="https://lh3.googleusercontent.com/FWft2Vdy90eIB5TjIqovS7fkzCUTj_eG3Lj3VfCWSSOgDQmm25iCsJC5RRUHdui9c0sRg1sASeWX5JmvgpD-kDwtZridFyvRac_avft7PWnoPtqvzG-NUg6fCyHu6FEpjLWqZeOOO_0DceGmTDxqFP_3BERmtu7-gjWUdE5S07Z6BnWHwUESvBhIIsWwFjjrg70sciLjp34WJtukiVz5b628HNvyvT9C5ipof07N-oma7bmBXIgULOmV3S62VoyWrMHTGc8J-DGI1cZwecQjO5zj9COH0MqV7C3jQspOHGUqjE60raoju8duNwPXLHchcQlKEJRQQFLv6FJDrcMcr-9zU6fP8HkkKNFJ176Vyy_iok_v7FkYfORVQF-OcyMkRq0LZtEgFyC8pxeLjmbJxM_vdRgb3uyfhKBK__bgws6KOJ_kEk64cAjBjPbx0ykmbKuvxnEZq9QbRwXKuNSQRrCXFxK1tHom2H1JwGk5tz00kMxdnHey07mQBaaK4hzoiyAHETfKZensaZBp5_Mn97q9DVi2Uf2QdUINiT7pmQGZvsqp9uoZwspzAQdFHXpBIQU7X52sETilmlYb6ATQcG93H3fJ8NqtKUCIz931yEC9FA=w312-h455-no">
</p>

Here is their article on Medium explaining the system:
[https://blog.gnosis.pm/a-slack-to-combat-phishing-scams-8019c20fc474](https://blog.gnosis.pm/a-slack-to-combat-phishing-scams-8019c20fc474)

**Comment by kitblake** [comment]
That's a clever approach. It certainly raises the barrier to entry (and requires dependencies) so it'll probably be effective in keeping scammers out. Although it's not bulletproof. But Gnosis has reached a success level where they can afford to be strict. Plus GNO is easy to acquire.

IMHO: For RChain it's too early for such measures. There is not much community and we want it to organically grow. Stumbling blocks, especially barriers to the standard "let's check out this community" platform of Slack, will deter people from joining. And at this point obtaining RHOC is rather involved. 

> "In the future, we are considering making it a requirement to deposit GNO into a contract where we can burn/transfer them in case the user misbehaves to further discourage scammers." 

I wish Slack had a read/write separation. Guest users are welcome to read but if you want to write then you need stricter permissions. Maybe you need to post a bond :)

But I'm excited to see that, in order to register for an invite, you just need to possess some tokens, as opposed to pay. We can definitely make use of that!

**Comment by patrick727** [comment]
I like the theory of this, it'd be cool to have people stake tokens as the enter a channel and lose them if they misbehave. 

It is early for that right now though, but maybe there is a separate channel for activists to work on, like can this be done with github? Something where moderators can stake on behave of noobs, which they receive if the milestone is reached

**Comment by lapin7** [comment]
RHOC's are not easy available at the moment. So we cannot yet implement the
Gnosis solution.
Our github collaboration is troll free afaik.
On the other hand, I've some good news. I've been talking to Greg and he
allowed me to use a budget under my control of 100,000 RHOC to be spend on
small Activist Tasks.

So it makes now sense to work out the spreadsheet that Jim has set up.
https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit#gid=0

There we can first agree on allocation of budget and after that approving
rewards that Activist claim and of course immediate payment after consensus
of peers.



--
Cheers,
HJ

**Comment by drbloom** [comment]
Agreed. Too early.
Consider such an option if we outgrow the current Slack team, or need to set up a separate forum for paid coop members. (Initial Membership documents are nearing completion. ETA Aug 28)
