### ISSUE TITLE
Transparency of financial details

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#92]
Contracts have been signed with people that do essential work for the Coop. How do we go about making the financial information public?

**Comment by lapin7** [comment]
I think this gsheet can be shared for "comment access".
https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit?usp=sharing

**Comment by lapin7** [comment]
I've set the access properties to only a few people, because of email-addresses.
But what happens if a sheet is protected and hidden? Is it still visible to everybody?

**Comment by kitblake** [comment]
When I try to access that sheet with other browsers and other Gmail accounts, the server says "You need permission. Ask for access, or switch to an account with permission.". 
It seems there are two options:
1. The setting is either "Anyone with the link can view/comment/edit"
2. Or, it's "Link sharing OFF - only specific people can access"

So because of the email addresses I suppose the sheet should only be shared with "specific people": iow those email addresses, and possibly management. It's not visible to everybody.

**Comment by lapin7** [comment]
**## A way to make data public**
Please check if assumptions below are correct:

- I've created a new file that imports the data from the original file. 
- The ranges can be set as such that there's no email visible. The ranges cannot be changed by a viewer
- The new file has access as "comment only".
- People can set individually their own filters on the data.
- A copy of the new file requests new access permissions to the original file.
- 

new file: [Pub Budget Allocation-Spending](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=1377988053)
org file: [RChain Activist RHOC Distribution](https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit#gid=1801970706&fvid=200986362)

Used: IMPORTRANGE("1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM","Rewards 201708!a1:af300")

**Comment by kitblake** [comment]
When I view the new file I see "Comment only". 

I notice that in the new file, the Rewards 201709 sheet for september has no formulas any more, only values. 
In the org file, the Rewards 201709 sheet for september still has formulas while the Rewards 201708 sheet for august does not. It only has values which makes sense because the month is closed.

If the goal is to be transparent and make the activist rewards visible to anybody (with the link), I think the easiest way is to create a base file named "RChain Activist Monthly Rewards" or such. We set the permissions on that to "Anybody with the link" so its publicly accessible.
Then at the end of every month we use the "Copy to..." function (in the tab) to copy the 'valued' Rewards sheet for the closed month into the publicly commentable file. 

Does that suffice? Or am I missing a key requirement..

**Comment by lapin7** [comment]
Sweet that you see "Comment only"
In my version Tab Rewards 201709 has still formulas (luckily 👍 )
Probably it has to do with the fact that you're on "Comment only"now. I will check that with another account.
The transparency is at the moment done through a pub version: [Pub Budget Allocation-Spending](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=1377988053)

And input can be done through form [Budget Allocation and - Spending](https://docs.google.com/forms/d/e/1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA/viewform)

When I'm done with the sheets, we can discuss further the access rights or how to do things.
